// _viewlayers/react/app/components/App/App.js
import React from 'react';
import Input from '../Input/Input';
import Paragraph from '../Paragraph/Paragraph';

const App = () => {
  const title = 'React TEST';
  const path = '/components/App.js';
  return (
    <div>
      <h1>{title}</h1>
      <p>This file can be found at {path}</p>
      <Input />
      <Paragraph />
    </div>
  );
};

export default App;

// _viewlayers/vue/app/components/app/App.vue
<template>
  <div class="vue-app">
    <h1>{{ message }}</h1>
    <p>You can edit this file at {{ path }}</p>
    <CustomInput />
    <paragraph />
  </div>
</template>

<script>
  import CustomInput from 'components/input/Input.vue';
  import Paragraph from 'components/paragraph/Paragraph.vue';

  export default {
    data() {
      return {
        message: 'hey there!',
        path: 'app/components/app/App.vue',
      };
    },
    computed: {
    },
    components: {
      CustomInput,
      Paragraph,
    },
  };
</script>
